config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  get 'sessions/new'
  	resources :posts do
	    collection do
	    	post :confirm
	    end
  	end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :update, :edit]
  resources :favorites, only: [:create, :destroy, :index]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	validates :content, length: { within: 1..140 }
	mount_uploader :image, ImageUploader
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
	validates :name,  presence: true, length: { maximum: 30 }
	validates :email, presence: true, length: { maximum: 255 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
	before_validation { email.downcase! }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
	has_many :posts
	mount_uploader :profil, ProfilUploader
	has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper
	before_action :login_required

	private

	def login_required
		redirect_to new_session_path unless current_user
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def index
		@favorites = current_user.favorites.all
	end

	def create
		favorite = current_user.favorites.create(post_id: params[:post_id])
		redirect_to posts_path, notice: "#{favorite.post.user.name}'S post has been added to favorites"
	end

	def destroy
		favorite = current_user.favorites.find_by(id: params[:id]).destroy
		redirect_to posts_path, notice: "#{favorite.post.user.name}Unposted Mr.'s post"
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:edit, :update, :show, :destroy]
	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = current_user.posts.build(post_params)
		if params[:back]
	  		render :new
		else
		    if @post.image.present?
		    	@picture = current_user
  				PictureMailer.picture_mail(@picture).deliver 
			end

			if @post.save
				redirect_to posts_path, notice: "Post created!"
			else
				render :new
			end
		end
	end

	def confirm
		@post = current_user.posts.build(post_params)
		render :new if @post.invalid?
	end

	def edit
	end

	def update
		if @post.update(post_params)
	  		redirect_to posts_path, notice: "Post edited!"
		else
	  		render :edit
		end
	end

	def show
		@favorite = current_user.favorites.find_by(post_id: @post.id)
	end

	def destroy
		@post.destroy
		redirect_to posts_path, notice:"Post deleted!"
	end

	private

	def post_params
		params.require(:post).permit(:content,:image,:image_cache)
	end

	def set_post
		@post = Post.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to posts_path()
    else
      flash.now[:danger] = 'I failed to login'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'Deconnected'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
        redirect_to user_path(@user.id), notice: "Profil edited!"
    else
        render :edit
    end
  end
  
  def show
  	@user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                              	 :password_confirmation, :profil, :profil_cache)
  end

  def user_profil_params
    params.require(:user).permit(:name, :email,:profil, :profil_cache)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create' || action_name == 'confirm' 
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
	@current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
	current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<br>
<% @favorites.each do |favorite| %>
  <table> 
    <div class="table">
      <tr>
        <th colspan="4">
          <% unless favorite.post.user.profil.blank? %>
            <span class="img"> <%= image_tag favorite.post.user.profil.url %></div>
          <%end%>

          <span>Posted by <%= favorite.post.user.name %> at <%= favorite.post.updated_at.to_date %></span>
          <hr>
        </th>
      </tr>
   
      <tr>
        <td>
          <p class="content"><%= favorite.post.content %></p>
          <% unless favorite.post.image.blank? %>
            <div class="img"> <%= image_tag favorite.post.image.url %></div>
          <%end%>
          <hr>
          <div class="btn_block">
            <div class="bloc"><i class="fas fa-info-circle"></i><%= link_to 'Show more!', post_path(favorite.post.id), class: "bloc" %></div>
          </div>
        </td>
      </tr>
    </div>
  </table>
  <br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task01</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  </head>

  <body>
    <% if flash[:notice] %>
      <div id="flash"><%= notice %></div>
    <% end %>
    <div class="contain">    
    <header class="clearfix">
      <div class="header-container">
        <div class="header_menu">
          <div class="left"><%= image_tag("insta.png", style: "height:90px;width:90px;") %></div>
          <div class="Text">InstaClone</div>

          <div class="">
          
          <% if logged_in? %>
            <div class="menu">
            <i class="fas fa-home"></i> <%= link_to "Home", posts_path,  class: "link" %> |
            <%= link_to 'New Post', new_post_path, class: "link" %> |
            <%= link_to 'Change Profil', edit_user_path(current_user.id), class: "link" %> |
            <%= link_to 'Fav list', favorites_path, class: "link" %> |
            <%= link_to "Logout", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "Sign up", new_user_path %> |
            <%= link_to "Login", new_session_path %>
          </div>
          <% end %>
          </div>
        </div>
      </div>
    </header>
    </div>
    <section class="section">
      <%= yield %>
    </section>
    <footer>
      © ︎ divecorp 2021 - Instagramclone
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>!!We've got <%= @post.errors.count %> errors!!</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="post">
    <p>What are news?</p>
    <div class="form">
      <%= form.text_field :content, placeholder: "Write something here...", class: "text"%>
        <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
        <%= form.file_field :image %>
        <%= form.hidden_field :image_cache %>
    </div>
    <br>
    <%= form.submit "Post", class: "submit" %>
  </div>
<% end %>

app/views/posts/confirm.html.erb
<h3>The following information is to be sent.</h3>
<div class="post">
	<%= form_with(model: @post, url: posts_path, local: true) do |form| %>
		<%= form.hidden_field :content %>
		<p>Content: <%= @post.content %></p>
		<%= image_tag(@post.image.url) if @post.image && @post.image.url %>
		<%= form.hidden_field :image_cache %>
		<%= form.submit  "Register", class: "submit" %>
		<%= form.submit "Return", name: "back", class: "submit" %>
	<% end %>
</div>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= render 'form' %>

app/views/posts/index.html.erb
<br>
<% @posts.each do |post| %>
  <table> 
    <div class="table">
      <tr>
        <th colspan="4">
          <% unless post.user.profil.blank? %>
            <span class="img"> <%= image_tag post.user.profil.url %></div>
          <%end%>

          <span>Posted by <%= post.user.name %> at <%= post.updated_at.to_date %></span>
          <hr>
        </th>
      </tr>
    
      <tr>
        <td>
          <p class="content"><%= post.content %></p>
          <% unless post.image.blank? %>
            <div class="img"> <%= image_tag post.image.url %></div>
          <%end%>
          <hr>
          <div class="btn_block">
            <div class="bloc"><i class="fas fa-info-circle"></i><%= link_to 'Show more!', post_path(post.id), class: "bloc" %></div>
            <%if current_user.id == post.user.id%>
              <div class="bloc"><i class="fas fa-edit"></i><%= link_to "Edit", edit_post_path(post.id), data: { confirm: 'Are you sure you want to edit this?'}, class: "bloc" %></div>
              <div class="bloc"><i class="fas fa-trash-alt"></i><%= link_to 'Delete', post_path(post.id), method: :delete ,data: { confirm: 'Are you sure you want to delete this?'}, class: "bloc" %></div>
            <%end%>
          </div>
        </td>
      </tr>
    </div>
  </table>
  <br>
<% end %>

app/views/posts/new.html.erb
<h2>Create post</h2>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1>More informations</h1>
<div class="post">
	<p>Tweeted by you at: <%= @post.created_at %> and Updated at <%= @post.updated_at %> by <%= @post.user.name %> </p>
	<hr>
	<p>Content: <%= @post.content %></p>
	<div>
		<%unless @post.image.blank? %>
			<%= image_tag @post.image.url %>
		<%end%>
	</div>
	<% unless @post.user_id == current_user.id %>
		<% if @favorite.present? %>
			<%= link_to 'Remove favorite', favorite_path(id: @favorite.id), method: :delete %>
		<% else %>
			<%= link_to 'Favorite', favorites_path(post_id: @post.id), method: :post %>
		<% end %>
	<% end %>
</div>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true ) do |form| %>
  <br>
  <div class="user">
    <p>Change Profile?</p>
    <div class="form">
        <br>
        <%=form.label :Name %>
        <%= form.text_field :name, placeholder: "Name..." %> 
        <br>
        <br>
        <%=form.label :Email %>
        <%= form.email_field :email, placeholder: "Email..." %>
        <br>
        <br>
        <%= form.password_field :password, placeholder: "Password..." %>
        <br> 
        <br> 
        <%= form.password_field :password_confirmation, placeholder: "Password confirmation..." %>
        <br>
        <br>
        <%= form.file_field :profil %>
        <%= form.hidden_field :profil_cache %>
    </div>
    <br>
    <%= form.submit "Update", class: "submit" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1> 
<% if @user.errors.any? %> 
  <div id="error_explanation"> 
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2> 
    <ul> 
      <% @user.errors.full_messages.each do |message| %> 
        <li><%= message %></li> 
      <% end %> 
    </ul> 
  </div>
<% end %>

<div class="form">
  <%= form_with(model: @user, local: true) do |f| %>
    <br>
    <%= f.text_field :name, placeholder: "Name..." %> 
    <br>
    <br>
    <%= f.email_field :email, placeholder: "Email..." %>
    <br>
    <br> 
    <%= f.password_field :password, placeholder: "Password..." %>
    <br> 
    <br> 
    <%= f.password_field :password_confirmation, placeholder: "Password confirmation..." %> 
    <br>
    <br>
    <%= f.file_field :profil %>
    <%= f.hidden_field :profil_cache %>
    <%= f.submit "Create my account", class: "submit" %> 
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Profil de <%= @user.name %></h1>
<button> 
	<% unless @user.profil.blank? %>
		<span class="img"> <%= image_tag @user.profil.url %></div>
	<%end%>
</button>
<p>E-mail address: <%= @user.email %></p>